name: linting & tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v2
        with:
          node-vesrion: '16.x'
          
      - uses: paambaati/codeclimate-action@v3.2.0
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    with:
      coverageCommand: npm run coverage
      debug: true
      
      - run: make install
      
      - run: make lint

      - run: make test

  
